Manufacturer.create!([
  {slug: "adiva", name: "Adiva", website: "www.adiva-world.com", country: "IT", data: nil},
  {slug: "ajs", name: "AJS", website: "www.ajsmotorcycles.co.uk", country: "GB", data: nil},
  {slug: "aprilia", name: "Aprilia", website: "www.aprilia.com/my_EN/", country: "IT", data: nil},
  {slug: "aveta", name: "Aveta", website: "www.aveta.com.my", country: "MY", data: nil},
  {slug: "benelli", name: "Benelli", website: "www.benelli.com/my-en", country: "IT", data: nil},
  {slug: "bimota", name: "Bimota", website: "bimota.it/?lang=en", country: "IT", data: nil},
  {slug: "bkz", name: "BKZ", website: nil, country: nil, data: nil},
  {slug: "blueshark", name: "Blueshark", website: "blueshark.com.my", country: "MY", data: nil},
  {slug: "bmw", name: "BMW", website: "www.bmw-motorrad.com.my/en/home.html", country: "DE", data: nil},
  {slug: "brixton", name: "Brixton", website: "www.brixton-motorcycles.com/ms/", country: "AT", data: nil},
  {slug: "buell", name: "Buell", website: "www.buellmotorcycle.com", country: "US", data: nil},
  {slug: "can-am", name: "Can-Am", website: "brp-malaysia.com/can-am-onroad/", country: "CA", data: nil},
  {slug: "cfmoto", name: "CFMoto", website: "www.cfmotomalaysia.com.my", country: "CN", data: nil},
  {slug: "comel", name: "Comel", website: nil, country: nil, data: nil},
  {slug: "cmc", name: "CMC", website: "cmcmotorcycles.com.my", country: "CN", data: nil},
  {slug: "daelim", name: "DNA Daelim", website: "www.dnamotors.co.kr", country: "KR", data: nil},
  {slug: "daiichi", name: "Daiichi", website: "daiichimotor.com", country: "MY", data: nil},
  {slug: "demak", name: "Demak", website: "dncmotorcycle.com/", country: "MY", data: nil},
  {slug: "ducati", name: "Ducati", website: "www.ducati.com.my", country: "IT", data: nil},
  {slug: "fantic", name: "Fantic", website: "www.fantic.com/?lang=EN", country: "IT", data: nil},
  {slug: "gilera", name: "Gilera", website: "www.gilera.com", country: "IT", data: nil},
  {slug: "gpx", name: "GPX", website: "www.gpxmalaysia.my", country: "TH", data: nil},
  {slug: "harley-davidson", name: "Harley-Davidson", website: "harleypj.com", country: "US", data: nil},
  {slug: "honda", name: "Honda", website: "boonsiewhonda.com.my", country: "JP", data: nil},
  {slug: "husaberg", name: "Husaberg", website: nil, country: nil, data: nil},
  {slug: "husqvarna", name: "Husqvarna", website: "husqvarnamalaysia.my", country: "SE", data: nil},
  {slug: "hyosung", name: "Hyosung", website: "hyosungmotorcycles.co.uk", country: "KR", data: nil},
  {slug: "indian", name: "Indian", website: "www.indianmotorcycle.com.my", country: "US", data: nil},
  {slug: "italjet", name: "Italjet", website: "italjet.com.my", country: "IT", data: nil},
  {slug: "jawa", name: "Jawa", website: "www.jawamotorcycles.com", country: "IN", data: nil},
  {slug: "kawasaki", name: "Kawasaki", website: "www.kawasaki.com.my", country: "JP", data: nil},
  {slug: "kayo", name: "Kayo", website: "kayominigp.com", country: "CN", data: nil},
  {slug: "keeway", name: "Keeway", website: "www.keeway.my", country: "CN", data: nil},
  {slug: "ktm", name: "KTM", website: "www.ktmmalaysia.com", country: "AT", data: nil},
  {slug: "ktns", name: "KTNS", website: "www.ktn.com.my", country: "MY", data: nil},
  {slug: "kymco", name: "Kymco", website: "www.kymco.com/international", country: "TW", data: nil},
  {slug: "lambretta", name: "Lambretta", website: "www.lambretta.com", country: "IT", data: nil},
  {slug: "laverda", name: "Laverda", website: "", country: "IT", data: nil},
  {slug: "lima", name: "LIMA", website: "www.limamotorcycles.com/", country: "CN", data: nil},
  {slug: "mle", name: "MLE", website: "www.bikecontinent.com.my", country: "MY", data: nil},
  {slug: "modenas", name: "Modenas", website: "modenas.my", country: "MY", data: nil},
  {slug: "momos", name: "Momos", website: "mofaz.com/mofaz-motosikal/", country: "MY", data: nil},
  {slug: "moto-guzzi", name: "Moto Guzzi", website: "www.motoguzzi.com/my_EN/", country: "IT", data: nil},
  {slug: "moto-morini", name: "Moto Morini", website: "www.motomorini.my", country: "IT", data: nil},
  {slug: "mv-agusta", name: "MV Agusta", website: "www.mvagusta.com/my/en", country: "IT", data: nil},
  {slug: "mz", name: "MZ (Motorenwerke Zschopau GmbH)", website: "", country: "DE", data: nil},
  {slug: "naza", name: "Naza", website: "www.instagram.com/nazabikes/", country: "MY", data: nil},
  {slug: "nimota", name: "Nimota", website: "nimotamalaysia.wordpress.com", country: "MY", data: nil},
  {slug: "nitro", name: "Nitro", website: nil, country: nil, data: nil},
  {slug: "norton", name: "Norton", website: "nortonmotorcycles.com", country: "GB", data: nil},
  {slug: "ottimo", name: "Ottimo", website: "", country: "MY", data: nil},
  {slug: "petronas", name: "Petronas", website: nil, country: nil, data: nil},
  {slug: "piaggio", name: "Piaggio", website: "", country: "IT", data: nil},
  {slug: "royal-alloy", name: "Royal Alloy", website: "royalalloymalaysia.com", country: "GB", data: nil},
  {slug: "royal-enfield", name: "Royal Enfield", website: "www.royalenfield.com/my/en/home/", country: "IN", data: nil},
  {slug: "qj-motor", name: "QJ Motor", website: "www.qjmotor.my", country: "CN", data: nil},
  {slug: "scomadi", name: "Scomadi", website: "www.scomadi.co.uk", country: "GB", data: nil},
  {slug: "sherco", name: "Sherco", website: "www.sherco.com", country: "FR", data: nil},
  {slug: "skyteam", name: "Skyteam", website: "www.skyteam.cn", country: "CN", data: nil},
  {slug: "sm-sport", name: "SM Sport", website: "www.mforce.my/product/SMSport", country: "MY", data: nil},
  {slug: "steyr-daimler", name: "Steyr-Daimler-Puch", website: "", country: "DE", data: nil},
  {slug: "suzuki", name: "Suzuki", website: "www.suzuki.com.my", country: "JP", data: nil},
  {slug: "sym", name: "SYM", website: "www.sym.mforce.my", country: "TW", data: nil},
  {slug: "treeletrik", name: "Treeletrik", website: "treeletrik-ev.com", country: "MY", data: nil},
  {slug: "triumph", name: "Triumph", website: "www.triumph-motorcycles.my", country: "GB", data: nil},
  {slug: "tvs", name: "TVS", website: "www.dajumotors.com", country: "IN", data: nil},
  {slug: "vespa", name: "Vespa", website: "www.vespa.com/my_EN/", country: "IT", data: nil},
  {slug: "victory", name: "Victory", website: "", country: "US", data: nil},
  {slug: "wmoto", name: "WMOTO", website: "www.wmoto.my", country: "MY", data: nil},
  {slug: "x-moto", name: "X-MOTO", website: nil, country: nil, data: nil},
  {slug: "yamaha", name: "Yamaha", website: "www.yamaha-motor.com.my", country: "JP", data: nil},
  {slug: "yadea", name: "Yadea", website: "yadea.my", country: "CN", data: nil},
  {slug: "zero-engineering", name: "Zero Engineering", website: "http://www.zeroengineering.com", country: "JP", data: nil},
  {slug: "zesparii", name: "Zesparii", website: nil, country: nil, data: nil},
  {slug: "zontes", name: "Zontes", website: "zontesmalaysia.com", country: "CN", data: nil},
  {slug: "zeromotorcycles-com", name: "Zero Motorcycles", website: "zeromotorcycles.com", country: "US", data: nil}
])
Product.create!([
  {slug: "yamaha-y15zr", manufacturer_id: "71", category: "Underbone", manufacturer_category: "", model: "Y15ZR", model_code: "B17E", rrp: "9498.0", assembled_in: nil, seat_height_mm: 845, wheelbase_mm: 1290, length_mm: 1960, height_mm: 1080, width_mm: 670, ground_clearance_mm: 135, engine_description: "Liquid-cooled, 4-stroke SOHC", displacement: 150, max_power_ps: "14.9", max_power_rpm: 8500, max_torque_nm: "13.8", max_torque_rpm: 7000, cylinders: 1, cyl_bore: "57.0", cyl_stroke: "58.7", cyl_valves: 4, oil_capacity_l: "1.15", fuel: "Petrol", fuel_capacity_l: "4.2", consumption_lkm: nil, range_km: nil, drive_category: 0, transmission: "Manual", clutch: "", gears: 5, tyre_front: "70/90 R17", tyre_rear: "120/70 R17", tube: false, tyre_category: "Radial", wheel_front_in: 17, wheel_rear_in: 17, suspension_front: "", suspension_rear: "", kerb_weight_kg: 115, brake_front_desc: "", brake_rear_desc: "", battery_size: "", additional_features: "", data: ""},
  {slug: "aprilia-sr-gt-200", manufacturer_id: "3", category: "Scooter", manufacturer_category: "Urban Adventure", model: "SR GT 200", model_code: "SRGT", rrp: "19900.0", assembled_in: nil, seat_height_mm: 799, wheelbase_mm: 1350, length_mm: 1920, height_mm: nil, width_mm: 765, ground_clearance_mm: nil, engine_description: "Single Cylinder, 4-Stroke, 4-Valve, Liquid Cooled Engine", displacement: 174, max_power_ps: "17.6", max_power_rpm: 8500, max_torque_nm: "16.5", max_torque_rpm: 7000, cylinders: 1, cyl_bore: "61.5", cyl_stroke: "58.7", cyl_valves: 4, oil_capacity_l: nil, fuel: "Petrol", fuel_capacity_l: "9.0", consumption_lkm: 2, range_km: nil, drive_category: 0, transmission: "CVT", clutch: "", gears: nil, tyre_front: "110/80R14", tyre_rear: "130/70R13", tube: false, tyre_category: "Radial", wheel_front_in: 14, wheel_rear_in: 13, suspension_front: "", suspension_rear: "", kerb_weight_kg: nil, brake_front_desc: "", brake_rear_desc: "", battery_size: "", additional_features: "", data: ""},
  {slug: "aprilia-tuono-660", manufacturer_id: "3", category: "Sport", manufacturer_category: "", model: "Tuono 660", model_code: "", rrp: "77900.0", assembled_in: nil, seat_height_mm: 820, wheelbase_mm: nil, length_mm: nil, height_mm: 805, width_mm: nil, ground_clearance_mm: nil, engine_description: "Parallel-Twin Cylinder, Liquid-Cooled, DOHC Engine", displacement: 660, max_power_ps: "101.0", max_power_rpm: 10500, max_torque_nm: "67.0", max_torque_rpm: 8500, cylinders: 2, cyl_bore: "81.0", cyl_stroke: "63.9", cyl_valves: 4, oil_capacity_l: "15.0", fuel: "", fuel_capacity_l: "15.0", consumption_lkm: nil, range_km: nil, drive_category: 0, transmission: "Manual", clutch: "Wet, Multi-Plate", gears: 6, tyre_front: "120/70ZR17", tyre_rear: "180/55ZR17", tube: false, tyre_category: "Run Flat", wheel_front_in: 17, wheel_rear_in: 17, suspension_front: "USD Fork 120 mm", suspension_rear: "Single Shock 130 mm", kerb_weight_kg: 183, brake_front_desc: "", brake_rear_desc: "", battery_size: "", additional_features: "", data: ""},
  {slug: "aveta-ranger-max-explorer", manufacturer_id: "4", category: "Underbone", manufacturer_category: "Adventure Cub", model: "Ranger Max Explorer", model_code: "", rrp: "6988.0", assembled_in: nil, seat_height_mm: 760, wheelbase_mm: 1280, length_mm: 1920, height_mm: 1150, width_mm: 720, ground_clearance_mm: 180, engine_description: "Air Cooled Single", displacement: 127, max_power_ps: "10.2", max_power_rpm: 8000, max_torque_nm: "10.5", max_torque_rpm: 5500, cylinders: 1, cyl_bore: "54.0", cyl_stroke: "55.5", cyl_valves: 2, oil_capacity_l: "1.2", fuel: "Petrol", fuel_capacity_l: "8.5", consumption_lkm: nil, range_km: nil, drive_category: 0, transmission: "Manual", clutch: "Double Clutch ", gears: 4, tyre_front: "2.75-18", tyre_rear: "3.50-16", tube: false, tyre_category: "", wheel_front_in: 18, wheel_rear_in: 16, suspension_front: "Telescopic Fork", suspension_rear: "Dual Gas Charged Shock", kerb_weight_kg: 115, brake_front_desc: "Disc", brake_rear_desc: "Drum", battery_size: "", additional_features: "", data: ""},
  {slug: "aveta-srv-180", manufacturer_id: "4", category: "Underbone", manufacturer_category: "Super Moped", model: "SRV 180", model_code: "", rrp: "9998.0", assembled_in: nil, seat_height_mm: nil, wheelbase_mm: 1288, length_mm: 1940, height_mm: 1055, width_mm: 690, ground_clearance_mm: nil, engine_description: "Liquid-Cooled, DOHC Engine", displacement: 175, max_power_ps: "17.0", max_power_rpm: 8000, max_torque_nm: "15.5", max_torque_rpm: 7000, cylinders: 1, cyl_bore: "62.0", cyl_stroke: "57.8", cyl_valves: 2, oil_capacity_l: nil, fuel: "Petrol", fuel_capacity_l: "6.6", consumption_lkm: nil, range_km: nil, drive_category: 0, transmission: "Manual", clutch: "Wet, Multi-Plate", gears: 6, tyre_front: "90/80R17", tyre_rear: "120/70R17", tube: false, tyre_category: "", wheel_front_in: 17, wheel_rear_in: 17, suspension_front: "Telescopic Fork", suspension_rear: "Monoshock", kerb_weight_kg: 113, brake_front_desc: "Disc", brake_rear_desc: "Disc", battery_size: "", additional_features: "", data: ""}
])
